apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: seyio/webapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "web-app-service"
  namespace: webapp
  labels:
    app: "webapp"
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: webapp

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traffik-webapp
  namespace: webapp
spec:
  rules:
  - host: seyidevops-task2.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: web-app-service
          servicePort: 80
